// For this project development
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  // GlobalComponents for Volar
  export interface GlobalComponents {
    HcAffix: typeof import('../packages/hicor-ui')['HcAffix']
    HcAlert: typeof import('../packages/hicor-ui')['HcAlert']
    HcAside: typeof import('../packages/hicor-ui')['HcAside']
    HcAutocomplete: typeof import('../packages/hicor-ui')['HcAutocomplete']
    HcAvatar: typeof import('../packages/hicor-ui')['HcAvatar']
    HcBacktop: typeof import('../packages/hicor-ui')['HcBacktop']
    HcBadge: typeof import('../packages/hicor-ui')['HcBadge']
    HcBreadcrumb: typeof import('../packages/hicor-ui')['HcBreadcrumb']
    HcBreadcrumbItem: typeof import('../packages/hicor-ui')['HcBreadcrumbItem']
    HcButton: typeof import('../packages/hicor-ui')['HcButton']
    HcButtonGroup: typeof import('../packages/hicor-ui')['HcButtonGroup']
    HcCalendar: typeof import('../packages/hicor-ui')['HcCalendar']
    HcCard: typeof import('../packages/hicor-ui')['HcCard']
    HcCarousel: typeof import('../packages/hicor-ui')['HcCarousel']
    HcCarouselItem: typeof import('../packages/hicor-ui')['HcCarouselItem']
    HcCascader: typeof import('../packages/hicor-ui')['HcCascader']
    HcCascaderPanel: typeof import('../packages/hicor-ui')['HcCascaderPanel']
    HcCheckbox: typeof import('../packages/hicor-ui')['HcCheckbox']
    HcCheckboxButton: typeof import('../packages/hicor-ui')['HcCheckboxButton']
    HcCheckboxGroup: typeof import('../packages/hicor-ui')['HcCheckboxGroup']
    HcCol: typeof import('../packages/hicor-ui')['HcCol']
    HcCollapse: typeof import('../packages/hicor-ui')['HcCollapse']
    HcCollapseItem: typeof import('../packages/hicor-ui')['HcCollapseItem']
    HcCollapseTransition: typeof import('../packages/hicor-ui')['HcCollapseTransition']
    HcColorPicker: typeof import('../packages/hicor-ui')['HcColorPicker']
    HcContainer: typeof import('../packages/hicor-ui')['HcContainer']
    HcConfigProvider: typeof import('../packages/hicor-ui')['HcConfigProvider']
    HcDatePicker: typeof import('../packages/hicor-ui')['HcDatePicker']
    HcDialog: typeof import('../packages/hicor-ui')['HcDialog']
    HcDivider: typeof import('../packages/hicor-ui')['HcDivider']
    HcDrawer: typeof import('../packages/hicor-ui')['HcDrawer']
    HcDropdown: typeof import('../packages/hicor-ui')['HcDropdown']
    HcDropdownItem: typeof import('../packages/hicor-ui')['HcDropdownItem']
    HcDropdownMenu: typeof import('../packages/hicor-ui')['HcDropdownMenu']
    HcEmpty: typeof import('../packages/hicor-ui')['HcEmpty']
    HcFooter: typeof import('../packages/hicor-ui')['HcFooter']
    HcForm: typeof import('../packages/hicor-ui')['HcForm']
    HcFormItem: typeof import('../packages/hicor-ui')['HcFormItem']
    HcHeader: typeof import('../packages/hicor-ui')['HcHeader']
    HcIcon: typeof import('../packages/hicor-ui')['HcIcon']
    HcImage: typeof import('../packages/hicor-ui')['HcImage']
    HcImageViewer: typeof import('../packages/hicor-ui')['HcImageViewer']
    HcInput: typeof import('../packages/hicor-ui')['HcInput']
    HcInputNumber: typeof import('../packages/hicor-ui')['HcInputNumber']
    HcLink: typeof import('../packages/hicor-ui')['HcLink']
    HcMain: typeof import('../packages/hicor-ui')['HcMain']
    HcMenu: typeof import('../packages/hicor-ui')['HcMenu']
    HcMenuItem: typeof import('../packages/hicor-ui')['HcMenuItem']
    HcMenuItemGroup: typeof import('../packages/hicor-ui')['HcMenuItemGroup']
    HcOption: typeof import('../packages/hicor-ui')['HcOption']
    HcOptionGroup: typeof import('../packages/hicor-ui')['HcOptionGroup']
    HcPageHeader: typeof import('../packages/hicor-ui')['HcPageHeader']
    HcPagination: typeof import('../packages/hicor-ui')['HcPagination']
    HcPopconfirm: typeof import('../packages/hicor-ui')['HcPopconfirm']
    HcPopper: typeof import('../packages/hicor-ui')['HcPopper']
    HcProgress: typeof import('../packages/hicor-ui')['HcProgress']
    HcRadio: typeof import('../packages/hicor-ui')['HcRadio']
    HcRadioButton: typeof import('../packages/hicor-ui')['HcRadioButton']
    HcRadioGroup: typeof import('../packages/hicor-ui')['HcRadioGroup']
    HcRate: typeof import('../packages/hicor-ui')['HcRate']
    HcRow: typeof import('../packages/hicor-ui')['HcRow']
    HcScrollbar: typeof import('../packages/hicor-ui')['HcScrollbar']
    HcSelect: typeof import('../packages/hicor-ui')['HcSelect']
    HcSlider: typeof import('../packages/hicor-ui')['HcSlider']
    HcStep: typeof import('../packages/hicor-ui')['HcStep']
    HcSteps: typeof import('../packages/hicor-ui')['HcSteps']
    HcSubMenu: typeof import('../packages/hicor-ui')['HcSubMenu']
    HcSwitch: typeof import('../packages/hicor-ui')['HcSwitch']
    HcTabPane: typeof import('../packages/hicor-ui')['HcTabPane']
    HcTable: typeof import('../packages/hicor-ui')['HcTable']
    HcTableColumn: typeof import('../packages/hicor-ui')['HcTableColumn']
    HcTabs: typeof import('../packages/hicor-ui')['HcTabs']
    HcTag: typeof import('../packages/hicor-ui')['HcTag']
    HcText: typeof import('../packages/hicor-ui')['HcText']
    HcTimePicker: typeof import('../packages/hicor-ui')['HcTimePicker']
    HcTimeSelect: typeof import('../packages/hicor-ui')['HcTimeSelect']
    HcTimeline: typeof import('../packages/hicor-ui')['HcTimeline']
    HcTimelineItem: typeof import('../packages/hicor-ui')['HcTimelineItem']
    HcTooltip: typeof import('../packages/hicor-ui')['HcTooltip']
    HcTransfer: typeof import('../packages/hicor-ui')['HcTransfer']
    HcTree: typeof import('../packages/hicor-ui')['HcTree']
    HcTreeSelect: typeof import('../packages/hicor-ui')['HcTreeSelect']
    HcTreeV2: typeof import('../packages/hicor-ui')['HcTreeV2']
    HcUpload: typeof import('../packages/hicor-ui')['HcUpload']
    HcSpace: typeof import('../packages/hicor-ui')['HcSpace']
    HcSkeleton: typeof import('../packages/hicor-ui')['HcSkeleton']
    HcSkeletonItem: typeof import('../packages/hicor-ui')['HcSkeletonItem']
    HcStatistic: typeof import('../packages/hicor-ui')['HcStatistic']
    HcCheckTag: typeof import('../packages/hicor-ui')['HcCheckTag']
    HcDescriptions: typeof import('../packages/hicor-ui')['HcDescriptions']
    HcDescriptionsItem: typeof import('../packages/hicor-ui')['HcDescriptionsItem']
    HcResult: typeof import('../packages/hicor-ui')['HcResult']
    HcSelectV2: typeof import('../packages/hicor-ui')['HcSelectV2']
    HcWatermark: typeof import('../packages/hicor-ui')['HcWatermark']
    // hicor ui
    HcTopMenu: typeof import('../packages/hicor-ui')['HcTopMenu']
    HcTitle: typeof import('../packages/hicor-ui')['HcTitle']
    HcApplyButton: typeof import('../packages/hicor-ui')['HcApplyButton']
  }

  interface ComponentCustomProperties {
    $message: typeof import('../packages/hicor-ui')['HcMessage']
    $notify: typeof import('../packages/hicor-ui')['HcNotification']
    $msgbox: typeof import('../packages/hicor-ui')['HcMessageBox']
    $messageBox: typeof import('../packages/hicor-ui')['HcMessageBox']
    $alert: typeof import('../packages/hicor-ui')['HcMessageBox']['alert']
    $confirm: typeof import('../packages/hicor-ui')['HcMessageBox']['confirm']
    $prompt: typeof import('../packages/hicor-ui')['HcMessageBox']['prompt']
    $loading: typeof import('../packages/hicor-ui')['HcLoadingService']
  }
}

export {}
