// For this project development
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  // GlobalComponents for Volar
  export interface GlobalComponents {
    ElAffix: typeof import('../packages/hicor-ui')['ElAffix']
    ElAlert: typeof import('../packages/hicor-ui')['ElAlert']
    ElAside: typeof import('../packages/hicor-ui')['ElAside']
    ElAutocomplete: typeof import('../packages/hicor-ui')['ElAutocomplete']
    ElAvatar: typeof import('../packages/hicor-ui')['ElAvatar']
    ElBacktop: typeof import('../packages/hicor-ui')['ElBacktop']
    ElBadge: typeof import('../packages/hicor-ui')['ElBadge']
    ElBreadcrumb: typeof import('../packages/hicor-ui')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('../packages/hicor-ui')['ElBreadcrumbItem']
    ElButton: typeof import('../packages/hicor-ui')['ElButton']
    ElButtonGroup: typeof import('../packages/hicor-ui')['ElButtonGroup']
    ElCalendar: typeof import('../packages/hicor-ui')['ElCalendar']
    ElCard: typeof import('../packages/hicor-ui')['ElCard']
    ElCarousel: typeof import('../packages/hicor-ui')['ElCarousel']
    ElCarouselItem: typeof import('../packages/hicor-ui')['ElCarouselItem']
    ElCascader: typeof import('../packages/hicor-ui')['ElCascader']
    ElCascaderPanel: typeof import('../packages/hicor-ui')['ElCascaderPanel']
    ElCheckbox: typeof import('../packages/hicor-ui')['ElCheckbox']
    ElCheckboxButton: typeof import('../packages/hicor-ui')['ElCheckboxButton']
    ElCheckboxGroup: typeof import('../packages/hicor-ui')['ElCheckboxGroup']
    ElCol: typeof import('../packages/hicor-ui')['ElCol']
    ElCollapse: typeof import('../packages/hicor-ui')['ElCollapse']
    ElCollapseItem: typeof import('../packages/hicor-ui')['ElCollapseItem']
    ElCollapseTransition: typeof import('../packages/hicor-ui')['ElCollapseTransition']
    ElColorPicker: typeof import('../packages/hicor-ui')['ElColorPicker']
    ElContainer: typeof import('../packages/hicor-ui')['ElContainer']
    ElConfigProvider: typeof import('../packages/hicor-ui')['ElConfigProvider']
    ElDatePicker: typeof import('../packages/hicor-ui')['ElDatePicker']
    ElDialog: typeof import('../packages/hicor-ui')['ElDialog']
    ElDivider: typeof import('../packages/hicor-ui')['ElDivider']
    ElDrawer: typeof import('../packages/hicor-ui')['ElDrawer']
    ElDropdown: typeof import('../packages/hicor-ui')['ElDropdown']
    ElDropdownItem: typeof import('../packages/hicor-ui')['ElDropdownItem']
    ElDropdownMenu: typeof import('../packages/hicor-ui')['ElDropdownMenu']
    ElEmpty: typeof import('../packages/hicor-ui')['ElEmpty']
    ElFooter: typeof import('../packages/hicor-ui')['ElFooter']
    ElForm: typeof import('../packages/hicor-ui')['ElForm']
    ElFormItem: typeof import('../packages/hicor-ui')['ElFormItem']
    ElHeader: typeof import('../packages/hicor-ui')['ElHeader']
    ElIcon: typeof import('../packages/hicor-ui')['ElIcon']
    ElImage: typeof import('../packages/hicor-ui')['ElImage']
    ElImageViewer: typeof import('../packages/hicor-ui')['ElImageViewer']
    ElInput: typeof import('../packages/hicor-ui')['ElInput']
    ElInputNumber: typeof import('../packages/hicor-ui')['ElInputNumber']
    ElLink: typeof import('../packages/hicor-ui')['ElLink']
    ElMain: typeof import('../packages/hicor-ui')['ElMain']
    ElMenu: typeof import('../packages/hicor-ui')['ElMenu']
    ElMenuItem: typeof import('../packages/hicor-ui')['ElMenuItem']
    ElMenuItemGroup: typeof import('../packages/hicor-ui')['ElMenuItemGroup']
    ElOption: typeof import('../packages/hicor-ui')['ElOption']
    ElOptionGroup: typeof import('../packages/hicor-ui')['ElOptionGroup']
    ElPageHeader: typeof import('../packages/hicor-ui')['ElPageHeader']
    ElPagination: typeof import('../packages/hicor-ui')['ElPagination']
    ElPopconfirm: typeof import('../packages/hicor-ui')['ElPopconfirm']
    ElPopper: typeof import('../packages/hicor-ui')['ElPopper']
    ElProgress: typeof import('../packages/hicor-ui')['ElProgress']
    ElRadio: typeof import('../packages/hicor-ui')['ElRadio']
    ElRadioButton: typeof import('../packages/hicor-ui')['ElRadioButton']
    ElRadioGroup: typeof import('../packages/hicor-ui')['ElRadioGroup']
    ElRate: typeof import('../packages/hicor-ui')['ElRate']
    ElRow: typeof import('../packages/hicor-ui')['ElRow']
    ElScrollbar: typeof import('../packages/hicor-ui')['ElScrollbar']
    ElSelect: typeof import('../packages/hicor-ui')['ElSelect']
    ElSlider: typeof import('../packages/hicor-ui')['ElSlider']
    ElStep: typeof import('../packages/hicor-ui')['ElStep']
    ElSteps: typeof import('../packages/hicor-ui')['ElSteps']
    ElSubMenu: typeof import('../packages/hicor-ui')['ElSubMenu']
    ElSwitch: typeof import('../packages/hicor-ui')['ElSwitch']
    ElTabPane: typeof import('../packages/hicor-ui')['ElTabPane']
    ElTable: typeof import('../packages/hicor-ui')['ElTable']
    ElTableColumn: typeof import('../packages/hicor-ui')['ElTableColumn']
    ElTabs: typeof import('../packages/hicor-ui')['ElTabs']
    ElTag: typeof import('../packages/hicor-ui')['ElTag']
    ElText: typeof import('../packages/hicor-ui')['ElText']
    ElTimePicker: typeof import('../packages/hicor-ui')['ElTimePicker']
    ElTimeSelect: typeof import('../packages/hicor-ui')['ElTimeSelect']
    ElTimeline: typeof import('../packages/hicor-ui')['ElTimeline']
    ElTimelineItem: typeof import('../packages/hicor-ui')['ElTimelineItem']
    ElTooltip: typeof import('../packages/hicor-ui')['ElTooltip']
    ElTransfer: typeof import('../packages/hicor-ui')['ElTransfer']
    ElTree: typeof import('../packages/hicor-ui')['ElTree']
    ElTreeSelect: typeof import('../packages/hicor-ui')['ElTreeSelect']
    ElTreeV2: typeof import('../packages/hicor-ui')['ElTreeV2']
    ElUpload: typeof import('../packages/hicor-ui')['ElUpload']
    ElSpace: typeof import('../packages/hicor-ui')['ElSpace']
    ElSkeleton: typeof import('../packages/hicor-ui')['ElSkeleton']
    ElSkeletonItem: typeof import('../packages/hicor-ui')['ElSkeletonItem']
    ElStatistic: typeof import('../packages/hicor-ui')['ElStatistic']
    ElCheckTag: typeof import('../packages/hicor-ui')['ElCheckTag']
    ElDescriptions: typeof import('../packages/hicor-ui')['ElDescriptions']
    ElDescriptionsItem: typeof import('../packages/hicor-ui')['ElDescriptionsItem']
    ElResult: typeof import('../packages/hicor-ui')['ElResult']
    ElSelectV2: typeof import('../packages/hicor-ui')['ElSelectV2']
    ElWatermark: typeof import('../packages/hicor-ui')['ElWatermark']
    // hicor ui
    ElTopMenu: typeof import('../packages/hicor-ui')['ElTopMenu']
    ElTitle: typeof import('../packages/hicor-ui')['ElTitle']
    ElApplyButton: typeof import('../packages/hicor-ui')['ElApplyButton']
  }

  interface ComponentCustomProperties {
    $message: typeof import('../packages/hicor-ui')['ElMessage']
    $notify: typeof import('../packages/hicor-ui')['ElNotification']
    $msgbox: typeof import('../packages/hicor-ui')['ElMessageBox']
    $messageBox: typeof import('../packages/hicor-ui')['ElMessageBox']
    $alert: typeof import('../packages/hicor-ui')['ElMessageBox']['alert']
    $confirm: typeof import('../packages/hicor-ui')['ElMessageBox']['confirm']
    $prompt: typeof import('../packages/hicor-ui')['ElMessageBox']['prompt']
    $loading: typeof import('../packages/hicor-ui')['ElLoadingService']
  }
}

export {}
