import '@hicor-ui/components/base/style/css'
import '@hicor-ui/components/input/style/css'
import '@hicor-ui/components/tag/style/css'
import '@hicor-ui/components/option/style/css'
import '@hicor-ui/components/option-group/style/css'
import '@hicor-ui/components/scrollbar/style/css'
import '@hicor-ui/components/popper/style/css'
import '@hicor-ui/theme-chalk/hc-select.css'
