blank_issues_enabled: false
contact_links:
  - name: Create new issue
    url: https://issue.hicor-ui.org/
    about: The issue which is not created via https://issue.hicor-ui.org/ will be closed immediately.
