import '@hicor-ui/components/base/style/css'
import '@hicor-ui/components/input/style/css'
import '@hicor-ui/components/tag/style/css'
import '@hicor-ui/components/scrollbar/style/css'
import '@hicor-ui/components/popper/style/css'
import '@hicor-ui/components/virtual-list/style/css'
import '@hicor-ui/theme-chalk/hc-select-v2.css'
