import '@hicor-ui/components/base/style'
import '@hicor-ui/theme-chalk/src/table.scss'
import '@hicor-ui/components/checkbox/style'
import '@hicor-ui/components/tooltip/style'
import '@hicor-ui/components/scrollbar/style'
