import '@hicor-ui/components/base/style/css'
import '@hicor-ui/theme-chalk/hc-container.css'
import '@hicor-ui/theme-chalk/hc-aside.css'
import '@hicor-ui/theme-chalk/hc-footer.css'
import '@hicor-ui/theme-chalk/hc-header.css'
import '@hicor-ui/theme-chalk/hc-main.css'
