import '@hicor-ui/components/base/style/css'
import '@hicor-ui/theme-chalk/el-container.css'
import '@hicor-ui/theme-chalk/el-aside.css'
import '@hicor-ui/theme-chalk/el-footer.css'
import '@hicor-ui/theme-chalk/el-header.css'
import '@hicor-ui/theme-chalk/el-main.css'
