export const PKG_PREFIX = '@hicor-ui'
export const PKG_NAME = 'hicor-ui'
export const PKG_CAMELCASE_NAME = 'HicorUi'
export const PKG_CAMELCASE_LOCAL_NAME = 'HicorUiLocale'
export const PKG_BRAND_NAME = 'Hicor Ui'
